// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
alias(libs.plugins.android.application) apply false
}
dependencies {
    //implementation 'androidx.viewpager2:viewpager2:1.0.0'
    //implementation 'com.google.android.material:material:1.4.0' // 或更高版本
    //implementation 'com.google.code.gson:gson:2.11.0'
}
